import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import { getServerSupabase } from '@/lib/supabaseServer';
import { LogoutButton } from '@/components/LogoutButton';
import { ToastProvider } from '@/components/Toast';

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const supabase = getServerSupabase();
  const { data: { user } } = await supabase.auth.getUser();
  let isAdmin = false;
  let resume: { slug: string; title: string } | null = null;
  if (user) {
    const { data: profile } = await supabase.from('profiles').select('role').eq('id', user.id).maybeSingle();
    isAdmin = profile?.role === 'admin';
    const { data: lessons } = await supabase
      .from('lessons')
      .select('id, slug, title, published, is_intro, day, sort_order')
      .eq('published', true)
      .order('is_intro', { ascending: false })
      .order('day', { ascending: true, nullsFirst: true })
      .order('sort_order', { ascending: true });
    if (lessons?.length) {
      const { data: progress } = await supabase
        .from('progress')
        .select('lesson_id, completed_at')
        .eq('user_id', user.id);
      const completedIds = new Set((progress ?? []).filter(p => p.completed_at).map(p => p.lesson_id));
      const next = lessons.find(l => !completedIds.has(l.id));
      resume = next ? { slug: next.slug, title: next.title } : null;
    }
  }
  return (
    <html lang="en">
      <body className={`${poppins.variable} antialiased`}>
        <header className="sticky top-0 z-40 w-full border-b bg-white/80 backdrop-blur supports-[backdrop-filter]:bg-white/60">
          <div className="mx-auto flex h-14 max-w-6xl items-center justify-between px-4">
            <a href="/dashboard" className="font-semibold">SEO Playbook</a>
            <nav className="flex items-center gap-3 text-sm">
              <a href="/dashboard" className="hover:underline">Dashboard</a>
              {resume && (
                <a href={`/lesson/${resume.slug}`} className="hover:underline">Resume</a>
              )}
              <a href="/perks" className="hover:underline">Perks</a>
              <a href="/favorites" className="hover:underline">Favorites</a>
              {isAdmin && (
                <>
                  <a href="/admin/lessons" className="hover:underline">Lessons</a>
                  <a href="/admin/offers" className="hover:underline">Admin Offers</a>
                  <a href="/admin/events" className="hover:underline">Events</a>
                </>
              )}
              {user ? <LogoutButton /> : <a href="/login" className="hover:underline">Login</a>}
            </nav>
          </div>
        </header>
        <ToastProvider>
          <div className="min-h-[calc(100svh-56px)]">{children}</div>
        </ToastProvider>
      </body>
    </html>
  );
}
